# 容器 配置
server:
  port: 443
  ssl:
    key-store: classpath:any.jks
    key-password: 214174460510953
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 数据库 及 Redis 配置    
spring:
  redis:
    host: localhost
#  使用 MySQL 不用做任何修改
  datasource:
    url: jdbc:mysql://localhost:3306/any_db?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10

# Mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true    # 驼峰命名转换
